In [2]:
import numpy as np
import time

In [17]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [19]:
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("vectorizaed " + str(1000*(toc - tic)) +"ms")
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("for loop " +str(1000*(toc - tic))+"ms")

249984.2467488594
vectorizaed 5.42140007019043ms
249984.2467488603
for loop 644.0458297729492ms


# Vectorizing Logistic Regression

In [5]:
X = np.array([[1,2,3],[4,5,6],[1,0.5, 2]])

In [11]:
w = np.array([[1],[2],[3]])

In [13]:
b = np.array([[1,0.5, 2]])

In [14]:
b

array([[1. , 0.5, 2. ]])

In [27]:
z = np.dot(w.T, X) +b

In [28]:
z 

array([[13., 14., 23.]])

In [23]:
x =np.arange(3,3)

In [24]:
x

array([], dtype=int64)

In [29]:
a = [[1,2,3], [5,6,7]]

In [30]:
b = [1,3,4]

In [31]:
a+b

[[1, 2, 3], [5, 6, 7], 1, 3, 4]

In [32]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [33]:
c.shape

(2, 3)

In [34]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [35]:
c.shape

(2, 3)

In [36]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [37]:
c.shape

(12288, 45)

In [40]:
# a.shape = (3,4)
# b.shape = (4,1)

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

ValueError: setting an array element with a sequence.

In [41]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [42]:
c

array([[-0.8463646 , -0.37257879, -0.41614096],
       [ 0.64216322,  1.19072254,  1.54593695],
       [-2.23091865, -1.21076497,  1.33040258]])

In [43]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [48]:
image.shape[2]

2

In [50]:
image.reshape(image.shape[0]*image.shape[1]*image.shape[2])

array([0.67826139, 0.29380381, 0.90714982, 0.52835647, 0.4215251 ,
       0.45017551, 0.92814219, 0.96677647, 0.85304703, 0.52351845,
       0.19981397, 0.27417313, 0.60659855, 0.00533165, 0.10820313,
       0.49978937, 0.34144279, 0.94630077])

In [3]:
import numpy as np
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)

In [4]:
B

array([[ 0.03173809],
       [-1.62036465],
       [-1.10399775],
       [ 0.73987237]])

In [5]:
A

array([[-0.79135949,  0.78010945,  0.04298813],
       [-1.5091528 , -0.94113743,  0.82992558],
       [-0.41866418, -0.47829217, -0.2070414 ],
       [-0.99556011,  0.99231091,  0.74312157]])